# Generated by Django 3.2.19 on 2023-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Gaming', 'Gaming'), ('Food', 'Food'), ('Traveling', 'Traveling'), ('Home', 'Home'), ('Activities', 'Activities')], default='Sport', max_length=30),
        ),
    ]
