# Generated by Django 3.2.19 on 2023-07-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(default='hello', max_length=500),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
